name: Deploy

on:
  push:
    branches: [  ]

jobs:
  build:
    name: Heroku Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "flick-backend"
          heroku_email: "bansallakshya94128@gmail.com"